---
title: "hierarchical-example"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{hierarchical-example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ncvi)
```

This is a work-in-progress tutorial for using `ncvi` with a hierarchical Bayesian model

### Example 1

The model:
$$
\begin{align}
    \begin{split}
        y_g &\sim \text{Pois}(\text{exp}[X\beta_g]) \\
        \beta_g &\sim \text{MVN}(\mu_0, \Sigma_0) \\
        \mu_0 &\sim \text{MVN}(0, \sigma^2\text{I}_p) \\
        r_i &\overset{ind}{\sim} \text{Gamma}(a_i, b_i) \\
        \tau = \frac{1}{\sigma^2} &\sim \text{Gamma}(a_\tau,b_\tau)
    \end{split}
\end{align}
$$

$\Sigma_0 = \text{diag}(v)$ where $\{1/v_i\} \subset \{r_i\}$ and $\{r_i\}$ is a set of precision parameters. For this example, I'll take the simplest case that $\Sigma_0 = \sigma^2_\beta \text{I}_p$.

Simulate data:

```{r ex1sim}
set.seed(558)
at <- 1
bt <- 2
ar <- 1
br <- 2
P <- 2
G <- 10
N <- 10

# t <- rgamma(1, shape = at, rate = bt)
# 
# r <- rgamma(1, shape = ar, rate = br)

t <- 1

r <- 1/3

mu0 <- mvtnorm::rmvnorm(1, mean = rep(0, P), sigma = diag(1/t, P))

beta <- mvtnorm::rmvnorm(G, mean = mu0, sigma = diag(1/r, P))

X <- cbind(1, kronecker(diag(1, P),rep(1, N/P))[, 2:P])

H <- diag(P)

eta_mat <- apply(beta, 1, function(b) X%*%b)

eta <- c(apply(beta, 1, function(b) X%*%b))

y <- rpois(N*G, lambda = exp(eta))

eta
y
```

Construct arguments to `fit_ncvi()`:

```{r }
y_list <- list()

for (i in seq(1, G)) {
  
  y_list[[i]] <- y[((i - 1) * N + 1):(i * N)]
  
}

data <- list(
  y = y_list,
  C = X,
  H = H,
  G = G
)

init_phi <- list()
lapply(y_list, function(x) log(mean(x)))
for (i in seq(1, G)) {
  
  init_phi[[i]] <- list(
    mu = rep(0, P),
    Sigma = diag(P))
  
}
init_phi
init_theta <- list(
  M = rep(0, P),
  R = diag(P),
  Tau = diag(r, P),
  t = t,
  r = r
)

init <- list(
  phi = init_phi,
  theta = init_theta
)

priors <- list(
  a = ar,
  b = br,
  at = at,
  bt = bt
)

update_phi_pkg <- function(data, pars, differentials) {
  
  phi <- pars$phi
  theta <- pars$theta
  y <- data$y
  C <- data$C
  G <- data$G
  
  for (i in seq(1, G)) {
    
    phi[[i]] <- nc_update_mvn(data = list(y = y[[i]], C = C), 
                              pars = list(phi = phi[[i]], theta = theta),
                              differentials = differentials)
    
  }
  
  # return phi
  phi
  
}

update_theta_pkg <- function(data, pars, priors) {
  
  theta <- pars$theta
  
  pars_mu0 <- conjugate_update_mvn_hierarchical_mean(pars)
  
  theta$M <- pars_mu0$M
  
  theta$R <- pars_mu0$R
  
  # return theta
  theta
  
}

differentials <- list(
  Sigma = function(data, pars) {
    d_mvn_cov(data, pars, d_mvn_cov_poisson)
  },
  mu = function(data, pars) {
    d_mvn_mean(data, pars, d_mvn_mean_poisson)
  }
)

options = list(max_iter = 1000,
               elbo_delta = 0.1,
               verbose = T)
```

Fit the model: 

```{r ex1fit}
tryCatch({
  fit_ncvi(data, init,
           update_phi = update_phi_pkg, 
           update_theta = update_theta_pkg,
           elbo = elbo_hierarchical,
           options = options,
           differentials = differentials,
           priors = priors)
  },
 error = function(err) {
    print(paste("error:", err))
    })
```

```{r testing}
# fit <- fit_ncvi(data, init,
#            update_phi = update_phi_pkg,
#            update_theta = update_theta_pkg,
#            elbo = elbo_hierarchical,
#            options = options,
#            differentials = differentials,
#            priors = priors)
# 
# lapply(fit$phi, function(x) x$mu)
# 
# 
# source("../../vmp/minimal_examples/ex4_hierarchical2group.R")
# data_vb <- list(y = y_list, 
#                 etc = list(X = X, 
#                            t = r, 
#                            s = t, 
#                            G = G))
# 
# # construct initial values list 
# SigmaBinit <- list()
# for (i in seq(1,G)) {
#   SigmaBinit[[i]] <- diag(P)
# }
# 
# EBinit <- list()
# for (i in seq(1,G)) {
#   EBinit[[i]] <- rep(0,P)
# }
# 
# init_vb <- list(phi = list(EB = EBinit, 
#                            SigmaB = SigmaBinit),
#                 theta = list(EM = rep(0,P)))
# options_vb <- list(elbo_delta = 0.00001)
# differentials_vb <- list(SigmaB = differential_SigmaB, 
#                       EB = differential_EB)
# 
# fit_vb <- ncvmp(data = data_vb, 
#                 init = init_vb, 
#                 differentials = differentials_vb,
#                 update_phi = update_phi,
#                 update_theta = update_theta,
#                 elbo = elbo,
#                 options = options)
# 
# fit_vb$phi$EB
```

### Example 2: random effects 
